FROM jenkins/jenkins:lts

# if we want to install via apt
USER root
#RUN apt-get update
#RUN apt-get install apt-transport-https ca-certificates curl software-properties-common curl -y
#RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
#RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

#RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
#RUN apt-get update && apt-get install -y apt-utils docker.io && usermod -aG docker Jenkins
#RUN usermod -aG docker Jenkins
#RUN groups
RUN apt-get update && \
	apt-get -y install apt-transport-https \
	     ca-certificates \
	     curl \
	     gnupg2 \
	     software-properties-common && \
	curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg > /tmp/dkey; apt-key add /tmp/dkey && \
	add-apt-repository \
	   "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
	   $(lsb_release -cs) \
	   stable" && \
	apt-get update && \
	apt-get -y install docker-ce && usermod -aG docker jenkins

# drop back to the regular jenkins user - good practice
USER jenkins

